[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault = "G5XrK1ohfcszkjU2JM7WGbAY362U9YiWXYvMoY6NW5KG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\artis\.config\solana\id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
