[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "41qgvkHGcNozGUuEqyAvV7dF1DZKqAdrw6oJ9pePVuXe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "C:/Users/artis/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
